import '../globals.css';
import type { Metadata } from 'next';
import Providers from './providers';
import { ClerkProvider } from '@clerk/nextjs';
import { Montserrat } from 'next/font/google';
import { ReduxProvider } from '@/redux/ReduxProvider';

const montserrat = Montserrat({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['italic', 'normal'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxProvider>
      <ClerkProvider>
        <html lang="en">
          <body>
            <Providers>
              <main className={montserrat.className}>{children}</main>
            </Providers>
          </body>
        </html>
      </ClerkProvider>
    </ReduxProvider>
  );
}
